[package]
name = "firefox-memlimit"
version = "0.1.0"
authors = ["schnusch"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"
env_logger = "*"
log = "*"
nix = "*"
tempfile = "*"
